# Generated by Django 4.1.7 on 2023-10-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='username',
            field=models.TextField(null=True, verbose_name='username'),
        ),
    ]
