# Generated by Django 4.1.7 on 2023-10-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_project', '0002_note_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='username',
        ),
    ]
