# Generated by Django 4.1.7 on 2023-10-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_project', '0003_remove_note_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
