# Generated by Django 4.1.7 on 2023-10-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_project', '0005_rename_username_note_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
